spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: CustomerDBHikariPool
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
# Schema database configurations      
db:
  schemas:
    customer:
      name: CustomerDBSchema
      connection:
        url: jdbc:postgresql://localhost:5432/marketing
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
      tables:
        - accounts
        - customers
      schema-file: classpath:schema/CustomerDBSchema.json
